name: image-demo
version: 0.0.0
summary: Image demo 
description: Image for demo

confinement: strict
base: core18
grade: stable


slots:
 dbus-image-demo:
   interface: dbus
   bus: session
   name: com.example.image_demo

apps:
  daemon:
    daemon: simple
    restart-condition: always
    command-chain:
      - bin/run-daemon
      - bin/wayland-launch
    command: bin/image_demo
    extensions: [flutter-master]
    environment:
      XDG_DATA_HOME: $SNAP_USER_DATA
      XDG_DATA_DIRS: $SNAP/usr/share
      GDK_GL: gles

  image-demo:
    command-chain:
      - bin/wayland-launch
    command: image_demo
    extensions: [flutter-master]
    environment:
      XDG_DATA_HOME: $SNAP_USER_DATA
      XDG_DATA_DIRS: $SNAP/usr/share
      GDK_GL: gles 

parts:
  # uet-lms:
  #   source: .
  #   plugin: flutter
  #   flutter-target: lib/main.dart
  #   build-packages:
  #     - libsecret-1-dev
  #     - libjsoncpp-dev
  #   stage-packages:
  #     - libsecret-1-dev
  #     - libjsoncpp-dev # The main entry-point file of the application

  mir-kiosk-snap-launch:
    plugin: dump
    source: https://github.com/MirServer/mir-kiosk-snap-launch.git
    override-build:  $SNAPCRAFT_PART_BUILD/build-with-plugs.sh opengl wayland
    stage-packages:
      - inotify-tools

  assets:
    plugin: nil
    stage-packages:
    - dmz-cursor-theme
    - fonts-dejavu
    - fonts-freefont-ttf
    - fonts-ubuntu

# architectures:
#   - build-on: amd64
#     run-on: [amd64, arm64]

layout:
  /usr/share/fonts:
    bind: $SNAP/usr/share/fonts
  /etc/fonts:
    bind: $SNAP/etc/fonts
  /usr/share/icons:
    bind: $SNAP/usr/share/icons


